### ISSUE TITLE
Compatibility with Spree 3.0?

### ISSUE THREAD

**Issue by marekolszewski** [goshippo/spree_shippo#3]
When I try to install this gem, I get the following error (while using spree 3.0). Is this gem compatible with the latest version of spree?

    Bundler could not find compatible versions for gem "spree_core":
      In snapshot (Gemfile.lock):
        spree_core (= 3.0.3)

      In Gemfile:
        spree_core (= 3.0.3) ruby

        spree_core (~> 3.0.0) ruby

        spree_core (~> 3.0.0) ruby

        spree_shippo_labels (>= 0) ruby depends on
          spree_core (~> 2.3.3) ruby

    Running `bundle update` will rebuild your snapshot from scratch, using only
    the gems in your Gemfile, which may resolve the conflict.

**Comment by mnowik** [comment]
Thanks for your interest in the Shippo Spree extension! This extension is for platform partners, who manage hundreds or thousands of individual Spree sub-stores. This extension allows these partners to automatically connect each store. Our current version doesn't support Spree 3.0. Unfortunately, it's not in our short-term roadmap to bump the version.

For individual stores, however, you can easily integrate your store directly on our platform at [https://goshippo.com/user/connect/](https://goshippo.com/user/connect/) by providing your ***Store URL***, ***Store Name*** and ***API Access Token***. 

If you have a specific request regarding the integration of multiple stores, please contact support@goshippo.com. Our team will help you find the best solution! If you're an individual store, just go ahead and connect instantly at [https://goshippo.com/user/connect/](https://goshippo.com/user/connect/).

Cheers,
Matt
